### ISSUE TITLE
no longer as accurate 

### ISSUE THREAD

**Issue by vignakke** [lugia19/DeltaMacros#2]
Hi, I came to see you because 2 weeks ago I made a macro for a game that was super accurate and did not miss any obstacle however I just noticed that it is no longer the case it no longer makes the mouse clicks at the right time 

PS: I forgot to mention it but it's an obstacle game on browser (I tried on brave / firefox / edge)

dont know if my cpu is in cause so 
![image](https://user-images.githubusercontent.com/69920044/152520496-2453dedf-0dab-4c21-a1eb-d02840d24a0a.png)

**Comment by lugia19** [comment]
Could you tell me what the game is, so I can test this?

Your CPU should be more than capable of handling the playback.

**Comment by vignakke** [comment]
> Could you tell me what the game is, so I can test this?
> 
> Your CPU should be more than capable of handling the playback.

hey it happens on several games, for example roblox and https://www.dogeruntoken.com/demo ( mostly on that one)

**Comment by vignakke** [comment]
ah yes, I had a request too I wanted to know if it was possible to add an option that would make it run in background (like the controlclick)

**Comment by lugia19** [comment]
I've tested this and yeah, I can see what you meant but I'm afraid it's not a matter of the recorder becoming less accurate, it's just that there's a limit to how accurate I could make it. Since it doesn't appear that mouse movement is required in that game you'd probably have more luck with a different macrorecorder.

As for teh background option, not really, since the script mainly centers around playing back mouse movement using deltas, which is not possible in the background.
